import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'ent1',
    difficulty: 'easy',
    question: 'Что делает декоратор @Entity({ name: \'movies\' })?',
    options: [
      'Регистрирует класс как таблицу и задаёт её имя movies в базе данных',
      'Подключает класс к AppModule и добавляет его в DI-контейнер NestJS-приложения',
      'Указывает TypeORM загружать данные из таблицы movies при старте сервера в память',
      'Создаёт таблицу',
    ],
    correct: 0,
    explanation: 'Без @Entity — это просто TypeScript-класс, TypeORM его не видит. @Entity регистрирует его как сущность. name задаёт реальное имя таблицы в Postgres — обычно lowercase во множественном числе.',
  },
  {
    id: 'ent2',
    difficulty: 'easy',
    question: 'Чем @PrimaryGeneratedColumn() отличается от @PrimaryGeneratedColumn(\'uuid\')?',
    options: [
      'uuid нельзя использовать с PostgreSQL — только с MySQL и SQLite',
      'Первый генерирует числа 1, 2, 3... Второй генерирует UUID-строки',
      'Никакой разницы — оба генерируют числовой автоинкремент',
      'uuid необходимо устанавливать отдельным пакетом помимо typeorm',
    ],
    correct: 1,
    explanation: '@PrimaryGeneratedColumn() → SERIAL в Postgres (1, 2, 3). @PrimaryGeneratedColumn(\'uuid\') → uuid4 строка вида a1b2c3... Поле при uuid становится string вместо number.',
  },
  {
    id: 'ent3',
    difficulty: 'easy',
    question: 'Что означает nullable: true в @Column?',
    options: [
      'Поле TypeScript становится опциональным — можно не передавать в конструктор',
      'TypeORM будет игнорировать это поле при синхронизации схемы с базой данных',
      'Колонка может содержать NULL — значение необязательно',
      'Поле будет удалено из JSON-ответа API если его значение равно null',
    ],
    correct: 2,
    explanation: 'Без nullable: true TypeORM создаёт колонку как NOT NULL — значение обязательно. nullable: true → колонка принимает NULL. Используй для необязательных полей вроде description или releaseDate.',
  },
  {
    id: 'ent4',
    difficulty: 'medium',
    question: 'Зачем unsigned: true у колонки с типом int?',
    options: [
      'Только положительные числа — отрицательные значения Postgres отклонит',
      'Автоматически генерирует следующее значение при создании новой записи',
      'Устанавливает минимальное значение 0 на уровне TypeScript без проверки в БД',
      'Хранит целое число как строку без знака минус для совместимости с API',
    ],
    correct: 0,
    explanation: 'unsigned: true говорит Postgres: это число только неотрицательное. Год выпуска фильма, количество просмотров, рейтинг голосов — числа где отрицательное значение бессмысленно.',
  },
  {
    id: 'ent5',
    difficulty: 'medium',
    question: '@Column({ type: \'decimal\', precision: 3, scale: 1 }) — какие числа сюда поместятся?',
    options: [
      '3 знака после запятой, одна цифра до неё',
      'Числа от 0.1 до 99.9 с одной цифрой после запятой',
      'precision — точность округления при SELECT, scale задаёт точность при INSERT',
      'Любые числа — precision и scale только для отображения в Beekeeper',
    ],
    correct: 1,
    explanation: 'precision — всего цифр в числе. scale — из них после запятой. precision: 3, scale: 1 → одна цифра после точки, две до: максимум 99.9. Число 100.0 уже не поместится (4 цифры).',
  },
  {
    id: 'ent6',
    difficulty: 'easy',
    question: 'Что автоматически делает @CreateDateColumn?',
    options: [
      'Добавляет валидацию что дата создания не может быть в прошлом',
      'При каждом save() обновляет значение на текущую дату и время',
      'Ставит текущую дату при первом INSERT и больше это поле не меняет',
      'Создаёт индекс по этой колонке для ускорения сортировки по дате',
    ],
    correct: 2,
    explanation: 'TypeORM сам подставляет new Date() при создании записи. Ты никогда не трогаешь это поле вручную. @UpdateDateColumn работает по-другому — он обновляется при каждом save().',
  },
  {
    id: 'ent7',
    difficulty: 'medium',
    question: 'Зачем писать name: \'release_year\' в @Column, если поле уже называется releaseYear?',
    options: [
      'Без name TypeORM не создаёт колонку — параметр обязателен для всех числовых полей',
      'В TypeScript пишем camelCase, в Postgres принято snake_case — name задаёт имя именно в БД',
      'Создаёт алиас для QueryBuilder — позволяет обращаться к полю по двум именам сразу',
      'Позволяет переименовать поле в JSON-ответе контроллера без изменения сущности',
    ],
    correct: 1,
    explanation: 'Без name TypeORM создаёт колонку с именем releaseyear — всё слитно в нижнем регистре. name: \'release_year\' даёт нормальный snake_case. В TypeScript обращаемся через releaseYear, в SQL через release_year.',
  },
  {
    id: 'ent8',
    difficulty: 'medium',
    question: 'Как правильно подключить TypeScript enum к колонке TypeORM?',
    options: [
      '@EnumColumn(Genre) — специальный декоратор для перечислений в TypeORM',
      'type: \'varchar\' и проверять значение вручную в сервисе перед каждым сохранением в базу',
      'type: \'enum\', enum: Genre — TypeORM создаст тип-перечисление прямо в Postgres',
      'Добавить @IsEnum(Genre) в DTO, TypeORM подхватит ограничение автоматически',
    ],
    correct: 2,
    explanation: 'type: \'enum\' + enum: Genre. TypeORM создаёт в Postgres собственный тип CREATE TYPE... AS ENUM. Попытка сохранить значение вне enum — ошибка на уровне БД, не только в TypeScript.',
  },
  {
    id: 'ent9',
    difficulty: 'hard',
    question: 'Добавил новое NOT NULL поле без default в entity. В таблице уже есть строки. Что произойдёт при synchronize: true?',
    options: [
      'TypeORM молча заполнит все старые строки нулевым значением для этого типа и продолжит',
      'Ошибка при старте: нельзя поставить NOT NULL — существующие строки не имеют значения',
      'TypeORM пропустит синхронизацию этой колонки и выведет предупреждение в лог',
      'Postgres добавит колонку как nullable, TypeORM поставит NOT NULL только для новых строк',
    ],
    correct: 1,
    explanation: 'Именно это происходило в уроке: ALTER TABLE ... ALTER COLUMN SET NOT NULL — ошибка, потому что старые строки уже в таблице без значения. Решение: добавить default или nullable: true, либо очистить таблицу.',
  },
  {
    id: 'ent10',
    difficulty: 'easy',
    question: 'Чем @UpdateDateColumn отличается от @CreateDateColumn?',
    options: [
      'UpdateDateColumn хранит дату в UTC, CreateDateColumn — в локальном времени сервера',
      'Ничем — оба ставят дату один раз при создании записи',
      'UpdateDateColumn обновляется при каждом save(), CreateDateColumn только при первом',
      'UpdateDateColumn нужно обновлять вручную, TypeORM не трогает это поле автоматически',
    ],
    correct: 2,
    explanation: 'CreateDateColumn → дата создания, ставится один раз и не меняется. UpdateDateColumn → дата последнего изменения, TypeORM обновляет её сам при каждом repository.save(entity).',
  },
];
