import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'ctrl1',
    difficulty: 'easy',
    question: 'Что делает @Controller(\'movies\') на классе?',
    options: [
      'Задаёт /movies как префикс для всех маршрутов класса',
      'Регистрирует класс в DI-контейнере как провайдер',
      'Создаёт сущность Movie с автоматическими CRUD-методами',
      'Запрещает прямой вызов через new MoviesController()',
    ],
    correct: 0,
    explanation: '@Controller(\'movies\') помечает класс как контроллер и задаёт префикс /movies. Все @Get, @Post и другие методы внутри класса автоматически получат этот префикс в начале URL.',
  },
  {
    id: 'ctrl2',
    difficulty: 'easy',
    question: 'Контроллер: @Controller(\'users\') + метод: @Get(\'me\'). Какой итоговый URL?',
    options: [
      '/me',
      '/users',
      '/users/me',
      '/me/users',
    ],
    correct: 2,
    explanation: 'URL складывается: префикс @Controller + путь метода. @Controller(\'users\') даёт /users, @Get(\'me\') добавляет /me. Результат: /users/me.',
  },
  {
    id: 'ctrl3',
    difficulty: 'easy',
    question: '@Controller() написан без параметров. Что происходит?',
    options: [
      'NestJS выбросит ошибку — параметр пути обязателен',
      'Маршруты класса будут доступны от корневого пути /',
      'Маршруты будут доступны по имени класса в нижнем регистре',
      'Маршрут станет недоступен пока не добавить строку',
    ],
    correct: 1,
    explanation: '@Controller() без аргумента — это пустой префикс. Метод @Get(\'films\') станет GET /films, а @Get() без пути — GET /. Никакой ошибки не будет.',
  },
  {
    id: 'ctrl4',
    difficulty: 'easy',
    question: 'Есть @Controller(\'movies\') с методом @Get(). Какой URL обработает этот метод?',
    options: [
      'GET /movies/get',
      'GET /movies',
      'GET /',
      'GET /movies/index',
    ],
    correct: 1,
    explanation: '@Get() без аргумента — это корень относительно контроллера. Если контроллер /movies, то @Get() = GET /movies. Чтобы получить /movies/all — нужно @Get(\'all\').',
  },
  {
    id: 'ctrl5',
    difficulty: 'medium',
    question: 'Что делает опция host в объекте @Controller({ path: \'movies\', host: \'api.site.ru\' })?',
    options: [
      'Задаёт имя хоста в документации Swagger',
      'Принимает запросы только с домена api.site.ru',
      'Проксирует запросы к внешнему серверу api.site.ru',
      'Включает CORS для домена api.site.ru в этом контроллере',
    ],
    correct: 1,
    explanation: 'host — это фильтр по заголовку Host входящего запроса. Если Host не совпадает — запрос не попадёт в этот контроллер. Удобно для мультитенантных приложений с несколькими доменами.',
  },
  {
    id: 'ctrl6',
    difficulty: 'medium',
    question: 'Где нужно вызывать app.setGlobalPrefix(\'api\')?',
    options: [
      'В main.ts до app.listen()',
      'В app.module.ts через параметр prefix декоратора @Module()',
      'В каждом контроллере через @Controller({ globalPrefix: \'api\' })',
      'В nest-cli.json в поле globalRoutePrefix',
    ],
    correct: 0,
    explanation: 'setGlobalPrefix вызывается на экземпляре app в main.ts, обязательно до app.listen(). После этого все маршруты всего приложения получат префикс /api.',
  },
  {
    id: 'ctrl7',
    difficulty: 'medium',
    question: 'Глобальный префикс api, контроллер @Controller(\'movies\'), метод @Get(\':id\'). Итоговый URL?',
    options: [
      '/movies/api/:id',
      '/api/:id',
      '/api/movies/:id',
      '/api/movies',
    ],
    correct: 2,
    explanation: 'Порядок сборки URL: глобальный префикс → prefix контроллера → путь метода. /api + /movies + /:id = /api/movies/:id. Глобальный префикс всегда идёт первым.',
  },
  {
    id: 'ctrl8',
    difficulty: 'medium',
    question: 'Нужно перенести все маршруты с /movies на /films. Что минимально изменить?',
    options: [
      'Переименовать все @Get(\'movies/...\') в @Get(\'films/...\')',
      'Изменить строку в @Controller с \'movies\' на \'films\'',
      'Добавить @Redirect(\'/films\') на класс контроллера',
      'Переименовать класс MoviesController → FilmsController',
    ],
    correct: 1,
    explanation: 'Префикс в @Controller() — единственная точка, где задаётся базовый путь всего контроллера. Меняем одну строку — меняются все маршруты класса. @Get методы трогать не нужно.',
  },
  {
    id: 'ctrl9',
    difficulty: 'hard',
    question: 'host: [\'api.a.ru\', \'api.b.ru\'] — что означает массив в поле host?',
    options: [
      'NestJS балансирует запросы между двумя доменами',
      'Контроллер принимает запросы с любого домена из списка',
      'NestJS проксирует запросы по очереди к каждому домену',
      'Ошибка TypeScript — host принимает только строку',
    ],
    correct: 1,
    explanation: 'host принимает строку или массив строк. Запрос попадёт в контроллер если заголовок Host совпадёт хотя бы с одним значением из массива. Удобно когда один контроллер должен отвечать на запросы с нескольких доменов.',
  },
  {
    id: 'ctrl10',
    difficulty: 'hard',
    question: 'Вызов: app.setGlobalPrefix(\'api\', { exclude: [\'/health\'] }). Что произойдёт?',
    options: [
      'Все маршруты кроме /health получат префикс /api',
      'NestJS выбросит ошибку — второй аргумент не поддерживается',
      '/health перестанет работать совсем — exclude значит удалить маршрут',
      '/health получит отдельный префикс /api-health вместо /api',
    ],
    correct: 0,
    explanation: 'exclude позволяет исключить отдельные пути из глобального префикса. /health останется на /health (без /api), все остальные маршруты получат /api. Удобно для health-check эндпоинтов, которые должны быть на корневом пути.',
  },
];
