import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'repo1',
    difficulty: 'easy',
    question: 'Зачем @InjectRepository(MovieEntity) в конструкторе сервиса?',
    options: [
      'Говорит DI-контейнеру: «дай мне репозиторий именно для этой сущности»',
      'Регистрирует MovieEntity в AppModule без явного указания в TypeOrmModule.forFeature',
      'Включает автоматическое кэширование всех запросов к таблице movies',
      'Создаёт новое подключение к базе данных специально для этого сервиса',
    ],
    correct: 0,
    explanation: 'Repository<MovieEntity> — это обёртка над конкретной таблицей. @InjectRepository указывает, для какой именно сущности нужен репозиторий. Без него DI не знает какой из репозиториев передать.',
  },
  {
    id: 'repo2',
    difficulty: 'easy',
    question: 'Что возвращает findOne() если запись не найдена?',
    options: [
      'Бросает NotFoundException автоматически',
      'null',
      'undefined',
      'Пустой объект {}',
    ],
    correct: 1,
    explanation: 'findOne() возвращает null — не исключение, не undefined. Поэтому после вызова нужно явно проверить: if (!movie) throw new NotFoundException(). TypeORM не знает какую ошибку бросать — это твоя задача.',
  },
  {
    id: 'repo3',
    difficulty: 'medium',
    question: 'В чём разница между repository.create(dto) и repository.save(entity)?',
    options: [
      'create() записывает в БД, save() только валидирует данные перед записью',
      'create() формирует JS-объект в памяти без SQL, save() делает INSERT или UPDATE в БД',
      'Никакой разницы — это два названия одной операции для совместимости',
      'create() используется для вставки, save() только для обновления существующей записи',
    ],
    correct: 1,
    explanation: 'create(dto) — это просто new MovieEntity() с данными из dto. В базу ничего не пишется. save(entity) — смотрит есть ли id: есть → UPDATE, нет → INSERT. Вот почему для создания нужны оба шага.',
  },
  {
    id: 'repo4',
    difficulty: 'medium',
    question: 'Как TypeORM понимает — делать INSERT или UPDATE при вызове save()?',
    options: [
      'Проверяет наличие поля id в объекте — есть id значит UPDATE, нет id значит INSERT',
      'Всегда делает INSERT и игнорирует id если он передан явно',
      'Делает SELECT перед каждым save() и проверяет существует ли такая строка',
      'Смотрит на createdAt — если поле заполнено значит это UPDATE',
    ],
    correct: 0,
    explanation: 'Простая логика: нет id → новая запись → INSERT. Есть id → запись уже существует → UPDATE. При create(dto) id не задан — поэтому save() делает INSERT и Postgres генерирует uuid.',
  },
  {
    id: 'repo5',
    difficulty: 'easy',
    question: 'Зачем Object.assign(movie, dto) перед save() при обновлении?',
    options: [
      'Без Object.assign TypeORM не знает какие поля нужно обновить в базе данных',
      'Копирует поля из dto в существующий объект чтобы save() увидел изменения',
      'Валидирует что все обязательные поля в dto совпадают с полями сущности',
      'Создаёт глубокую копию объекта чтобы не мутировать исходные данные сервиса',
    ],
    correct: 1,
    explanation: 'movie — это загруженный из БД объект с id. dto — новые данные. Object.assign(movie, dto) перезаписывает поля прямо в объект movie. Теперь movie.title = dto.title и так далее. save(movie) видит изменения и делает UPDATE.',
  },
  {
    id: 'repo6',
    difficulty: 'medium',
    question: 'Что принимает repository.remove() — id или объект сущности?',
    options: [
      'Только id в виде числа или строки',
      'Объект сущности — поэтому сначала нужно найти запись через findById',
      'Любое из двух — метод сам определяет тип аргумента',
      'Массив id для удаления нескольких записей одновременно',
    ],
    correct: 1,
    explanation: 'remove() принимает entity, не id. Это сделано намеренно: ты сначала ищешь запись (и обрабатываешь 404 если не нашёл), а потом удаляешь. Есть также delete({ id }) — принимает условие, но не возвращает удалённый объект.',
  },
  {
    id: 'repo7',
    difficulty: 'medium',
    question: 'Что делает опция take в find({ take: 10, skip: 0 })?',
    options: [
      'Ограничивает количество возвращаемых записей — аналог SQL LIMIT',
      'Устанавливает таймаут запроса в миллисекундах',
      'Выбирает только указанные поля из таблицы аналогично SELECT col1, col2',
      'Задаёт максимальный размер одной записи в байтах',
    ],
    correct: 0,
    explanation: 'take — это LIMIT, skip — OFFSET. take: 10, skip: 20 вернёт строки с 21 по 30. Стандартная основа пагинации. Страница N: skip = (N-1) * take.',
  },
  {
    id: 'repo8',
    difficulty: 'hard',
    question: 'Метод findById вызывается в update() и в delete(). Зачем выносить его отдельно?',
    options: [
      'Обязательное требование TypeORM — все findOne должны быть обёрнуты в отдельный метод',
      'Логика поиска и обработки 404 один раз — в одном месте. Дублировать if (!movie) throw ... везде хуже',
      'TypeScript не позволяет использовать await внутри условного блока напрямую',
      'findOne слишком медленный — отдельный метод включает кэширование результата',
    ],
    correct: 1,
    explanation: 'findById инкапсулирует: найти + проверить + бросить 404. Без него в update() и delete() пришлось бы копировать одну и ту же проверку. Изменить текст ошибки — один раз в findById, а не в трёх местах.',
  },
  {
    id: 'repo9',
    difficulty: 'hard',
    question: 'find({ where: { isAvailable: true } }) — что происходит если isAvailable нет в @Column сущности?',
    options: [
      'TypeORM проигнорирует условие и вернёт все записи без фильтрации',
      'Ошибка TypeScript: поле не существует в типе MovieEntity',
      'SQL-запрос выполнится но вернёт пустой массив',
      'TypeORM автоматически добавит колонку в схему через synchronize',
    ],
    correct: 1,
    explanation: 'where принимает Partial<Entity> — TypeScript проверит что поле существует в сущности. Если isAvailable не задекларировано в MovieEntity — ошибка компиляции. Это одна из причин почему типизация TypeORM полезна.',
  },
  {
    id: 'repo10',
    difficulty: 'easy',
    question: 'Нужно ли добавлять await перед repository.create(dto)?',
    options: [
      'Нет — create() синхронный, в БД не ходит',
      'Да — любой метод репозитория возвращает Promise',
      'Зависит от версии TypeORM — в старых синхронный, в новых асинхронный',
      'Да — без await сущность не валидируется перед сохранением',
    ],
    correct: 0,
    explanation: 'create() просто формирует объект в памяти — он синхронный. await нужен только там где реально идёт запрос в БД: find(), findOne(), save(), remove(). Лишний await не сломает код, но это признак непонимания что происходит.',
  },
];
