import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'par1',
    difficulty: 'easy',
    question: 'Что вернёт @Query(\'genre\') при запросе GET /movies?genre=action?',
    options: [
      '"action"',
      'Весь объект запроса',
      '{ genre: "action" }',
      'Поле genre из тела запроса',
    ],
    correct: 0,
    explanation: '@Query(\'genre\') извлекает значение конкретного query-параметра по имени. Результат — строка "action", а не объект.',
  },
  {
    id: 'par2',
    difficulty: 'easy',
    question: '@Query() без аргумента при запросе ?page=2&sort=asc вернёт...',
    options: [
      'Строку "page=2&sort=asc"',
      'Объект { page: "2", sort: "asc" }',
      'Первый параметр: "2"',
      'Undefined — без аргумента декоратор не работает',
    ],
    correct: 1,
    explanation: '@Query() без аргумента собирает ВСЕ query-параметры в один объект. Все значения приходят как строки — конвертация в число, если нужно, лежит на тебе.',
  },
  {
    id: 'par3',
    difficulty: 'easy',
    question: 'Маршрут @Get(\':id\'). Как получить значение :id внутри метода?',
    options: [
      '@Query(\'id\') id: string',
      '@Body(\'id\') id: string',
      '@Param(\'id\') id: string',
      '@Headers(\'id\') id: string',
    ],
    correct: 2,
    explanation: '@Param читает динамические сегменты URL — части пути с двоеточием. @Query — для ?key=value, @Body — для тела запроса, @Headers — для HTTP-заголовков.',
  },
  {
    id: 'par4',
    difficulty: 'easy',
    question: 'Чем @Body(\'title\') отличается от @Body()?',
    options: [
      'Они одинаковые',
      '@Body(\'title\') — одно поле, @Body() — весь объект тела',
      '@Body(\'title\') — работает только с GET, @Body() — с POST',
      '@Body(\'title\') требует указать тип, @Body() нет',
    ],
    correct: 1,
    explanation: '@Body(\'title\') достаёт одно конкретное поле из тела запроса. @Body() возвращает весь объект — обычно типизируется через DTO.',
  },
  {
    id: 'par5',
    difficulty: 'medium',
    question: 'Маршрут @Get(\':movieId/reviews/:reviewId\'). Запрос GET /movies/5/reviews/3. Что вернёт @Param()?',
    options: [
      '"5"',
      '"3"',
      '{ movieId: "5", reviewId: "3" }',
      '["5", "3"]',
    ],
    correct: 2,
    explanation: '@Param() без аргумента возвращает объект со всеми параметрами сразу. @Param(\'movieId\') вернул бы "5", @Param(\'reviewId\') — "3".',
  },
  {
    id: 'par6',
    difficulty: 'medium',
    question: 'Что вернёт @Headers(\'user-agent\')?',
    options: [
      'Строку — значение заголовка User-Agent',
      'Объект со всеми заголовками запроса',
      'Массив значений если заголовков несколько',
      'Строку в формате "user-agent: Mozilla/5.0"',
    ],
    correct: 0,
    explanation: '@Headers(\'user-agent\') возвращает строку — только значение. Ключ "user-agent" не включается в ответ. Сравни с @Headers() без аргумента — он вернёт весь объект заголовков.',
  },
  {
    id: 'par7',
    difficulty: 'medium',
    question: 'Если используешь @Res(), NestJS...',
    options: [
      'Всё равно автоматически отправит ответ после метода',
      'Ждёт что ты сам вызовешь res.send() или res.json()',
      'Выбросит ошибку если метод вернёт что-то через return',
      'Запрещает использовать другие декораторы в том же методе',
    ],
    correct: 1,
    explanation: 'Когда используешь @Res(), NestJS отключает автоматическую отправку ответа. Ты обязан сам вызвать res.json(), res.send() и т.д. — иначе запрос зависнет.',
  },
  {
    id: 'par8',
    difficulty: 'medium',
    question: 'Почему не стоит злоупотреблять @Req() и @Res()?',
    options: [
      'Они работают медленнее специализированных декораторов',
      'Жёсткая привязка к Express — при смене платформы и в тестах будут проблемы',
      'NestJS не поддерживает их вне контроллеров',
      'Они помечены как устаревшие в NestJS 10+',
    ],
    correct: 1,
    explanation: '@Req()/@Res() привязывают код к Express/Fastify. Если сменишь платформу или захочешь протестировать контроллер в изоляции — придётся мокировать весь объект запроса. Специализированные декораторы этой проблемы не имеют.',
  },
  {
    id: 'par9',
    difficulty: 'hard',
    question: 'Запрос: POST /movies?notify=true с телом { "title": "Dune" }. Что вернёт @Query(\'notify\')?',
    options: [
      'true (boolean)',
      '"true" (string)',
      '{ notify: true }',
      'Undefined — @Query не работает в POST-методах',
    ],
    correct: 1,
    explanation: 'Все query-параметры приходят как строки, вне зависимости от содержимого. "true" — это строка, не булевое значение. Если нужен boolean — конвертируй вручную или используй ValidationPipe с трансформацией.',
  },
  {
    id: 'par10',
    difficulty: 'hard',
    question: 'В одном методе нужно получить @Query() и @Body(). Это возможно?',
    options: [
      'Нет — каждый метод принимает только один декоратор параметра',
      'Да — можно комбинировать любые декораторы в одном методе',
      'Только если метод помечен как @Post',
      'Нет — @Query и @Body конфликтуют между собой',
    ],
    correct: 1,
    explanation: 'Декораторы параметров можно комбинировать как угодно: @Param, @Query, @Body, @Headers — все сразу в одном методе. Каждый читает свою часть запроса независимо.',
  },
];
