import type { QuizQuestion } from '@/components/ui/QuizBlock/QuizBlock';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'orm1',
    difficulty: 'easy',
    question: 'Что такое ORM?',
    options: [
      'Отдельный сервер для кэширования SQL-запросов',
      'Способ работать с БД через объекты вместо SQL вручную',
      'Библиотека для валидации данных перед сохранением',
      'Протокол шифрования соединения с базой данных',
    ],
    correct: 1,
    explanation: 'ORM — Object-Relational Mapping. Ты описываешь таблицы как TypeScript-классы, а ORM сам генерирует SQL. Вместо INSERT INTO ... VALUES ... пишешь repo.save(entity).',
  },
  {
    id: 'orm2',
    difficulty: 'easy',
    question: 'Какой пакет нужен для работы TypeORM именно с Postgres?',
    options: [
      'pg',
      'mysql2',
      'postgres-driver',
      '@types/postgres',
    ],
    correct: 0,
    explanation: 'pg — официальный драйвер PostgreSQL для Node.js. TypeORM использует его "под капотом" для соединения с базой. Для MySQL нужен mysql2, для SQLite — sqlite3.',
  },
  {
    id: 'orm3',
    difficulty: 'easy',
    question: 'Зачем нужен autoLoadEntities: true?',
    options: [
      'Сущности не нужно перечислять вручную в entities: []',
      'Создаёт все таблицы в базе данных при первом запуске приложения и заполняет их тестовыми данными',
      'Автоматически генерирует DTO-классы по существующей схеме базы данных',
      'Загружает все записи из таблиц в оперативную память Node.js при старте сервера',
    ],
    correct: 0,
    explanation: 'С autoLoadEntities: true достаточно зарегистрировать сущность через TypeOrmModule.forFeature([Entity]) — NestJS найдёт её сам. Без этого пришлось бы писать entities: [UserEntity, MovieEntity, ...] в AppModule.',
  },
  {
    id: 'orm4',
    difficulty: 'medium',
    question: 'Почему port: process.env.POSTGRES_PORT вызывает ошибку TypeScript?',
    options: [
      'POSTGRES_PORT — зарезервированное имя, TypeORM переименовывает его',
      'process.env возвращает string, а TypeORM ожидает number',
      'Переменные окружения недоступны в конфигурации TypeORM',
      'process.env работает только в main.ts, не в модулях',
    ],
    correct: 1,
    explanation: 'process.env всегда возвращает string | undefined — даже если в .env написано PORT=5433. TypeORM ждёт number. Решение: config.getOrThrow<number>(\'POSTGRES_PORT\').',
  },
  {
    id: 'orm5',
    difficulty: 'medium',
    question: 'Зачем в forRootAsync указывать imports: [ConfigModule]?',
    options: [
      'ConfigModule загружается до useFactory — иначе ConfigService не найден',
      'ConfigModule обязателен для любого динамического модуля в NestJS по умолчанию',
      'imports делает ConfigModule глобальным для всего приложения',
      'Без imports TypeORM не читает файл .env при инициализации модуля',
    ],
    correct: 0,
    explanation: 'useFactory выполняется асинхронно при инициализации модуля. Если ConfigModule не указан в imports — NestJS не гарантирует что он загрузится раньше useFactory. Итог: ConfigService не найден.',
  },
  {
    id: 'orm6',
    difficulty: 'medium',
    question: 'Зачем inject: [ConfigService] в forRootAsync?',
    options: [
      'Чтобы DI-контейнер передал ConfigService в useFactory',
      'Чтобы NestJS зарегистрировал ConfigService как провайдер внутри TypeORM-модуля и кэшировал его',
      'Без inject создаётся новый экземпляр ConfigService на каждый вызов useFactory',
      'inject помечает ConfigService как синглтон в контексте TypeORM-модуля приложения',
    ],
    correct: 0,
    explanation: 'useFactory — это обычная функция, не класс. DI-контейнер не может передать ей зависимости через конструктор. inject явно указывает: "передай ConfigService первым аргументом в функцию".',
  },
  {
    id: 'orm7',
    difficulty: 'easy',
    question: 'config.get(\'PORT\') и config.getOrThrow(\'PORT\') — в чём разница?',
    options: [
      'get → undefined если нет, getOrThrow → ошибка при старте',
      'getOrThrow возвращает Promise, get — синхронное значение',
      'getOrThrow кэширует значение после первого чтения, get — нет',
      'get работает только для строк, getOrThrow — для любых типов',
    ],
    correct: 0,
    explanation: 'config.get() вернёт undefined если переменная не найдена — и приложение запустится с ошибкой подключения позже. config.getOrThrow() упадёт сразу при старте с понятным сообщением. Используй getOrThrow.',
  },
  {
    id: 'orm8',
    difficulty: 'medium',
    question: 'synchronize: true — что это?',
    options: [
      'TypeORM изменяет схему БД чтобы она совпадала с сущностями',
      'Включает автоматические резервные копии базы данных при каждом запуске приложения в фоновом режиме',
      'Синхронизирует данные между несколькими репликами базы данных в режиме реального времени',
      'Блокирует все запросы на запись до тех пор пока схема таблиц не совпадёт с сущностями TypeORM',
    ],
    correct: 0,
    explanation: 'synchronize: true автоматически добавляет/изменяет колонки при старте. Если удалишь поле из сущности — TypeORM удалит колонку из таблицы вместе с данными. В проде используй миграции.',
  },
  {
    id: 'orm9',
    difficulty: 'hard',
    question: 'Зачем выносить конфиг TypeORM в отдельный файл typeorm.config.ts?',
    options: [
      'Это обязательное требование @nestjs/typeorm начиная с версии 10',
      'Отдельный файл автоматически валидирует переменные окружения при запуске',
      'Чище AppModule и проще переиспользовать конфиг для TypeORM CLI',
      'TypeORM сам находит файл typeorm.config.ts без явного импорта в AppModule',
    ],
    correct: 2,
    explanation: 'Две причины: AppModule остаётся чистым (вместо 15 строк конфига — одна строка useFactory: getTypeOrmConfig), и тот же файл можно переиспользовать для TypeORM CLI при работе с миграциями.',
  },
  {
    id: 'orm10',
    difficulty: 'hard',
    question: 'ConfigModule.forRoot({ isGlobal: true }) — что значит isGlobal?',
    options: [
      'Не нужно импортировать ConfigModule в каждый модуль',
      'Конфиг загружается из всех .env файлов в проекте одновременно и объединяется',
      'Переменные из .env автоматически попадают в глобальный объект process.env',
      'ConfigModule регистрирует все переменные как глобальные константы приложения',
    ],
    correct: 0,
    explanation: 'Без isGlobal: true пришлось бы добавлять ConfigModule в imports каждого модуля, где нужен ConfigService. С isGlobal: true — один раз в AppModule и ConfigService доступен везде.',
  },
];
